"""Explicit migration inventory. IDs do not depend on display names.

Keep every module accounted for; see docs/CATALOGUE.md and regression fixture.
"""

ALIASES = {"ping_ip": "ping"}

TOOL_SPECS = (
    {'id': 'asn_info', 'name': 'ASN Information', 'categories': ['NETWORK'], 'module': 'asn_info', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'banner_grabber', 'name': 'Banner Grabber', 'categories': ['DISCOVERY'], 'module': 'banner_grabber', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'blacklist_check', 'name': 'Blacklist Check', 'categories': ['NETWORK'], 'module': 'blacklist_check', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'dns_lookup_suite', 'name': 'DNS Lookup Suite', 'categories': ['DISCOVERY'], 'module': 'dns_lookup_suite', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'dns_records', 'name': 'DNS Records', 'categories': ['NETWORK'], 'module': 'dns_records', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'dns_resolver_compare', 'name': 'DNS Resolver Compare', 'categories': ['DISCOVERY'], 'module': 'dns_resolver_compare', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'dns_zone_transfer_test', 'name': 'Zone Transfer Test', 'categories': ['DISCOVERY'], 'module': 'dns_zone_transfer_test', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'domain_osint', 'name': 'Domain OSINT (Full)', 'categories': ['OSINT'], 'module': 'domain_osint', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'email_osint', 'name': 'Email OSINT', 'categories': ['OSINT'], 'module': 'email_osint', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'email_permutations', 'name': 'Email Permutations', 'categories': ['OSINT', 'INTEL'], 'module': 'email_permutations', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'favicon_hash', 'name': 'Favicon Hash', 'categories': ['DISCOVERY'], 'module': 'favicon_hash', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'file_hash_audit', 'name': 'File Hash Audit', 'categories': ['INTEL'], 'module': 'file_hash_audit', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'github_dork_pack', 'name': 'GitHub Dork Pack', 'categories': ['OSINT'], 'module': 'github_dork_pack', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'google_dork_generator', 'name': 'Google Dork Generator', 'categories': ['OSINT'], 'module': 'google_dork_generator', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'haveibeenpwned', 'name': 'Breach / Leak Check', 'categories': ['OSINT'], 'module': 'haveibeenpwned', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'host_header_probe', 'name': 'Host Header Probe', 'categories': ['WEB'], 'module': 'host_header_probe', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'http_headers', 'name': 'HTTP Headers Analysis', 'categories': ['WEB'], 'module': 'http_headers', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'http_title_probe', 'name': 'HTTP Title Probe', 'categories': ['DISCOVERY'], 'module': 'http_title_probe', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'image_metadata', 'name': 'Image Metadata / EXIF', 'categories': ['OSINT'], 'module': 'image_metadata', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'ioc_analyzer', 'name': 'IOC Analyzer', 'categories': ['INTEL'], 'module': 'ioc_analyzer', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'ip_lookup', 'name': 'IP Lookup / Geolocation', 'categories': ['NETWORK'], 'module': 'ip_lookup', 'entrypoint': 'IPLookupTool', 'kind': 'base'},
    {'id': 'ip_reputation_links', 'name': 'IP/Domain Reputation Links', 'categories': ['OSINT', 'INTEL'], 'module': 'ip_reputation_links', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'list_saved_results', 'name': 'Voir les resultats sauvegardes', 'categories': ['REPORTS'], 'module': 'list_saved_results', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'my_ip_info', 'name': 'My IP / Network Info', 'categories': ['NETWORK'], 'module': 'my_ip_info', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'netblock_host_counter', 'name': 'Netblock Host Counter', 'categories': ['NETWORK', 'INTEL'], 'module': 'netblock_host_counter', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'password_strength_estimator', 'name': 'Password Strength Estimator', 'categories': ['INTEL'], 'module': 'password_strength_estimator', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'phone_osint', 'name': 'Phone Number OSINT', 'categories': ['OSINT'], 'module': 'phone_osint', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'ping', 'name': 'Ping', 'categories': ['NETWORK'], 'module': 'ping', 'entrypoint': 'PingTool', 'kind': 'base'},
    {'id': 'ping_sweep_cidr', 'name': 'Ping Sweep CIDR', 'categories': ['DISCOVERY'], 'module': 'ping_sweep_cidr', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'port_scanner', 'name': 'Port Scanner', 'categories': ['NETWORK'], 'module': 'port_scanner', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'redirect_chain_analyzer', 'name': 'Redirect Chain Analyzer', 'categories': ['WEB'], 'module': 'redirect_chain_analyzer', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'report_generator', 'name': 'Generer un rapport', 'categories': ['REPORTS'], 'module': 'report_generator', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'reverse_dns', 'name': 'Reverse DNS', 'categories': ['NETWORK'], 'module': 'reverse_dns', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'robots_sitemap_audit', 'name': 'Robots / Sitemap Audit', 'categories': ['WEB'], 'module': 'robots_sitemap_audit', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'security_txt_audit', 'name': 'Security.txt Audit', 'categories': ['WEB'], 'module': 'security_txt_audit', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'shodan_search', 'name': 'Shodan Search', 'categories': ['OSINT'], 'module': 'shodan_search', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'social_media_lookup', 'name': 'Social Media Lookup', 'categories': ['OSINT'], 'module': 'social_media_lookup', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'ssl_cert_info', 'name': 'SSL Certificate Info', 'categories': ['WEB'], 'module': 'ssl_cert_info', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'subdomain_finder', 'name': 'Subdomain Finder', 'categories': ['OSINT'], 'module': 'subdomain_finder', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'subdomain_resolver', 'name': 'Subdomain Resolver', 'categories': ['DISCOVERY'], 'module': 'subdomain_resolver', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'subnet_calculator', 'name': 'Subnet Calculator', 'categories': ['NETWORK'], 'module': 'subnet_calculator', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'tcp_connect_test', 'name': 'TCP Connect Test', 'categories': ['NETWORK'], 'module': 'tcp_connect_test', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'tech_stack_detector', 'name': 'Tech Stack Detector', 'categories': ['OSINT', 'WEB'], 'module': 'tech_stack_detector', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'tls_version_probe', 'name': 'TLS Version Probe', 'categories': ['NETWORK', 'INTEL'], 'module': 'tls_version_probe', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'traceroute', 'name': 'Traceroute', 'categories': ['NETWORK'], 'module': 'traceroute', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'url_recon', 'name': 'URL Recon', 'categories': ['WEB'], 'module': 'url_recon', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'username_lookup', 'name': 'Username Search', 'categories': ['OSINT'], 'module': 'username_lookup', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'username_variations', 'name': 'Username Variations', 'categories': ['OSINT', 'INTEL'], 'module': 'username_variations', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'virustotal_check', 'name': 'VirusTotal Check', 'categories': ['OSINT'], 'module': 'virustotal_check', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'wayback_machine', 'name': 'Wayback Machine', 'categories': ['OSINT'], 'module': 'wayback_machine', 'entrypoint': 'run', 'kind': 'legacy'},
    {'id': 'whois_lookup', 'name': 'WHOIS Lookup', 'categories': ['NETWORK'], 'module': 'whois_lookup', 'entrypoint': 'run', 'kind': 'legacy'},
)
